# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
# This is for client only cuz I idk how to due with the backend stuff.

name: Node.js Package

on:
  release:
    types: [created]
  push:
    branches: 
      - main
    paths:
      - '**'
      - '!.github/workflows/**'
      - '!.gitignore'
      - '!**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: cd client # for client only
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - run: cd client # for client only
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}} #TODO: add a token @Marcus
